[package]
name = "my_gtfs"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
gtfs-structures = "0.41.3"
json5 = "0.4.1"
multimap = "0.10.0"
serde = { version = "1.0.204", features = ["derive"] }
spinoff = "0.8.0"
